### ISSUE TITLE
Got error on first run -  Unexpected keyword argument 'use_flash_attention_2'

### ISSUE THREAD

**Issue by HMDRAMS-DEV** [Vaibhavs10/insanely-fast-whisper#106]
Traceback (most recent call last):
  File "/opt/homebrew/bin/insanely-fast-whisper", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/insanely_fast_whisper/cli.py", line 78, in main
    pipe = pipeline(
           ^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/transformers/pipelines/__init__.py", line 788, in pipeline
    framework, model = infer_framework_load_model(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/transformers/pipelines/base.py", line 270, in infer_framework_load_model
    model = model_class.from_pretrained(model, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 467, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2611, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: WhisperForConditionalGeneration.__init__() got an unexpected keyword argument 'use_flash_attention_2'

**Comment by Vaibhavs10** [comment]
Hi @HMDRAMS-DEV - That should not happen. What your CLI command?

**Comment by HMDRAMS-DEV** [comment]
insanely-fast-whisper --file-name "/Users/ramialhamad/development/russo-dec-4.m4a" I tried it with an mp3 file as well, same error.

**Comment by Vaibhavs10** [comment]
hmm.. It looks like a similar to this: https://github.com/Vaibhavs10/insanely-fast-whisper/issues/107#issuecomment-1840862076

Can you run with similar args as mentioned in the linked comment.

**Comment by bluusun** [comment]
Had the same error on Linux. Solved with:

pip3 install transformers -U 

It seems you don't require the latest transformers needed as dependency.

**Comment by dannguyen** [comment]
Just in case anyone else stumbles on this: I'm on Windows 11/WSL 2/CUDA 12.6 and I was running into a similar problem with this error message about the argument `attn_implementation`

```
File "/home/danx/.pyenv/versions/3.11.5/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2966, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: WhisperForConditionalGeneration.__init__() got an unexpected keyword argument 'attn_implementation'
```

However, installing/upgrading transformers as per [bluusun's comment](https://github.com/Vaibhavs10/insanely-fast-whisper/issues/106#issuecomment-1846021072) fixed it: I was at `transformers-4.33.2`, the upgrade to `transformers-4.44.0` fixed it
