### ISSUE TITLE
Attempting to use `--timestamp word` crashes after a few seconds

### ISSUE THREAD

**Issue by alinsavix** [Vaibhavs10/insanely-fast-whisper#116]
Using insanely-fast-whisper 0.0.8 on python 3.11.7, attempting to use `--timestamp word` gives the following crash:
```
$ insanely-fast-whisper.exe --file-name stream_recording.wav --timestamp word --device-id 0 -flash true
You are attempting to use Flash Attention 2.0 with a model initialized on CPU. Make sure to move the model to GPU after initializing it on CPU with `model.to('cuda')`.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
🤗 Transcribing... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0:00:03
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\pipx\bin\insanely-fast-whisper.exe\__main__.py", line 7, in <module>
  File "C:\pipx\venvs\insanely-fast-whisper\Lib\site-packages\insanely_fast_whisper\cli.py", line 102, in main
    outputs = pipe(
              ^^^^^
  File "C:\pipx\venvs\insanely-fast-whisper\Lib\site-packages\transformers\pipelines\automatic_speech_recognition.py", line 357, in __call__
    return super().__call__(inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\pipx\venvs\insanely-fast-whisper\Lib\site-packages\transformers\pipelines\base.py", line 1132, in __call__
    return next(
           ^^^^^
  File "C:\pipx\venvs\insanely-fast-whisper\Lib\site-packages\transformers\pipelines\pt_utils.py", line 124, in __next__
    item = next(self.iterator)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\pipx\venvs\insanely-fast-whisper\Lib\site-packages\transformers\pipelines\pt_utils.py", line 266, in __next__
    processed = self.infer(next(self.iterator), **self.params)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\pipx\venvs\insanely-fast-whisper\Lib\site-packages\transformers\pipelines\base.py", line 1046, in forward
    model_outputs = self._forward(model_inputs, **forward_params)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\pipx\venvs\insanely-fast-whisper\Lib\site-packages\transformers\pipelines\automatic_speech_recognition.py", line 552, in _forward
    generate_kwargs["num_frames"] = stride[0] // self.feature_extractor.hop_length
                                    ~~~~~~~~~~^^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for //: 'tuple' and 'int'
```

This happens to me with both `--flash true` and `--flash false`. It does _not_ happen with `--timestamp chunk`.

Happy to provide whatever additional information you need, just not sure what would be useful here -- but let me know!

**Comment by Vaibhavs10** [comment]
Thanks for the bug report @alinsavix - This is a limitation. You can bypass this by passing `--batch-size 1` for now. This is quite less efficient but still get's the job done.

Here's the issue where we are tracking this: https://github.com/Vaibhavs10/insanely-fast-whisper/issues/40

(I'll close this issue in favor of the one linked, feel free to re-open if you feel otherwise 🤗)
