### ISSUE TITLE
Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by marsonal2023** [Vaibhavs10/insanely-fast-whisper#124]
raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
??

**Comment by Vaibhavs10** [comment]
Hi @marsonal2023 - Can you provide more details for the error? What CLI command are you using? What's your system configuration and so on?

**Comment by leoliu606** [comment]
(nf-whisper311) PS D:\ai\live-main\live-ts> insanely-fast-whisper --file-name https://alldogen.oss-cn-shanghai.aliyuncs.com/vd1106/a24591ce31ffb76fbbc28e1f34711e49/audio.webm
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\app\conda\envs\nf-whisper311\Scripts\insanely-fast-whisper.exe\__main__.py", line 7, in <module>
  File "D:\app\conda\envs\nf-whisper311\Lib\site-packages\insanely_fast_whisper\cli.py", line 78, in main
    pipe = pipeline(
           ^^^^^^^^^
  File "D:\app\conda\envs\nf-whisper311\Lib\site-packages\transformers\pipelines\__init__.py", line 1070, in pipeline
    return pipeline_class(model=model, framework=framework, task=task, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\app\conda\envs\nf-whisper311\Lib\site-packages\transformers\pipelines\automatic_speech_recognition.py", line 239, in __init__      
    self.model.to(device)
  File "D:\app\conda\envs\nf-whisper311\Lib\site-packages\transformers\modeling_utils.py", line 2460, in to
    return super().to(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\app\conda\envs\nf-whisper311\Lib\site-packages\torch\nn\modules\module.py", line 1160, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\app\conda\envs\nf-whisper311\Lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  File "D:\app\conda\envs\nf-whisper311\Lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  File "D:\app\conda\envs\nf-whisper311\Lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  File "D:\app\conda\envs\nf-whisper311\Lib\site-packages\torch\nn\modules\module.py", line 833, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "D:\app\conda\envs\nf-whisper311\Lib\site-packages\torch\nn\modules\module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\app\conda\envs\nf-whisper311\Lib\site-packages\torch\cuda\__init__.py", line 289, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
(nf-whisper311) PS D:\ai\live-main\live-ts>


wihndows , conda, python=3.11, nvidia4090,cuda118

@Vaibhavs10 Good

**Comment by marsonal2023** [comment]
yes what is what excatly happened to me too. google search results told me to reinsall torch but i already have it installed

**Comment by Vaibhavs10** [comment]
This looks like the same issue as the second question in the FAQ: https://github.com/Vaibhavs10/insanely-fast-whisper#frequently-asked-questions

This is a windows specific issue. The second question is known to fix this issue.

Sorry about this, packaging can be quite messy.

(feel free to re-open this issue if it doesn't fix)

**Comment by IsaackRasmussen** [comment]
For me, it helped to get the latest version by referencing the this repository when installing
https://github.com/Vaibhavs10/insanely-fast-whisper/issues/213
