### ISSUE TITLE
The model type whisper is not supported to be used with BetterTransformer

### ISSUE THREAD

**Issue by afiaka87** [Vaibhavs10/insanely-fast-whisper#133]
Hey, great project. Having trouble running on my CUDA/Python3.11 setup using the pipx install instructions from the README. 

## Invocation

```sh
insanely-fast-whisper --file-name 'redacted.opus'
```

## Stack trace
```sh

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/home/sam/.local/bin/insanely-fast-whisper", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/sam/.local/pipx/venvs/insanely-fast-whisper/lib/python3.11/site-packages/insanely_fast_whisper/cli.py", line 89, in main
    pipe.model = pipe.model.to_bettertransformer()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sam/.local/pipx/venvs/insanely-fast-whisper/lib/python3.11/site-packages/transformers/modeling_utils.py", line 4302, in to_bettertransformer
    return BetterTransformer.transform(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/sam/.local/pipx/venvs/insanely-fast-whisper/lib/python3.11/site-packages/optimum/bettertransformer/transformation.py", line 228, in transform
    raise NotImplementedError(
NotImplementedError: The model type whisper is not yet supported to be used with BetterTransformer. Feel free to open an issue at https://github.com/huggingface/optimum/issues if you would like this model type to be supported. Currently supported models are: dict_keys(['albert', 'bark', 'bart', 'bert', 'bert-generation', 'blenderbot', 'bloom', 'camembert', 'blip-2', 'clip', 'codegen', 'data2vec-text', 'deit', 'distilbert', 'electra', 'ernie', 'fsmt', 'gpt2', 'gptj', 'gpt_neo', 'gpt_neox', 'hubert', 'layoutlm', 'm2m_100', 'marian', 'markuplm', 'mbart', 'opt', 'pegasus', 'rembert', 'prophetnet', 'roberta', 'roc_bert', 'roformer', 'splinter', 'tapas', 't5', 'vilt', 'vit', 'vit_mae', 'vit_msn', 'wav2vec2', 'xlm-roberta', 'yolos']).
```
I searched the issues for a similar error (seems to be related to the use of `bettertransformers`). I only found one similar issue but it seemed to be dealing with problems for the `mps` backend, not `cuda` as I am using. I'm a bit rusty/unfamiliar with `bettertransformers` but if a fix is relatively simple I'd be happy to implement and PR it.

Any idea what might be going on? My first guess would be that I've wound up with an out-of-date version of bettertransformers somehow? Otherwise I'm not sure.

Thanks.

**Comment by astrowonk** [comment]
I had this same error but I went ahead and installed `flash-attn` per the instructions and the ran with `--flash True` and it worked. 

Though I had to do ` pipx runpip insanely-fast-whisper install wheel` before the flash install...

**Comment by oenu** [comment]
Similar issue, WSL2, Ubuntu W11
```
  File "/home/oenu/.local/pipx/venvs/insanely-fast-whisper/lib/python3.10/site-packages/optimum/bettertransformer/transformation.py", line 228, in transform
    raise NotImplementedError(
NotImplementedError: The model type whisper is not yet supported to be used with BetterTransformer. Feel free to open an issue at https://github.com/huggingface/optimum/issues if you would like this model type to be supported. Currently supported models are: dict_keys(['albert', 'bark', 'bart', 'bert', 'bert-generation', 'blenderbot', 'bloom', 'camembert', 'blip-2', 'clip', 'codegen', 'data2vec-text', 'deit', 'distilbert', 'electra', 'ernie', 'fsmt', 'gpt2', 'gptj', 'gpt_neo', 'gpt_neox', 'hubert', 'layoutlm', 'm2m_100', 'marian', 'markuplm', 'mbart', 'opt', 'pegasus', 'rembert', 'prophetnet', 'roberta', 'roc_bert', 'roformer', 'splinter', 'tapas', 't5', 'vilt', 'vit', 'vit_mae', 'vit_msn', 'wav2vec2', 'xlm-roberta', 'yolos']).
```

**Comment by Vaibhavs10** [comment]
Looks like the latest update to Transformers is causing this behaviour. Looking into it.

**Comment by oenu** [comment]
Am trying to work around this with a native W11 install, having more issues with pytorch
```
❯ python
Python 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> x = torch.rand(5, 3)
>>> print(x)
tensor([[0.5099, 0.0674, 0.0501],
        [0.4224, 0.6675, 0.8401],
        [0.1338, 0.2699, 0.7610],
        [0.8115, 0.3994, 0.2331],
        [0.8323, 0.3584, 0.8603]])
>>> import torch
>>> torch.cuda.is_available()
True
>>> exit()

~ took 19s
❯ insanely-fast-whisper --file-name C:\Users\XX\Downloads\12-07TF_GeorgianPG_V01.mp3
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\users\XX\.local\bin\insanely-fast-whisper.exe\__main__.py", line 7, in <module>
  File "C:\Users\XX\AppData\Local\pipx\pipx\venvs\insanely-fast-whisper\Lib\site-packages\insanely_fast_whisper\cli.py", line 78, in main
    pipe = pipeline(
           ^^^^^^^^^
  File "C:\Users\XX\AppData\Local\pipx\pipx\venvs\insanely-fast-whisper\Lib\site-packages\transformers\pipelines\__init__.py", line 1070, in pipeline
    return pipeline_class(model=model, framework=framework, task=task, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\AppData\Local\pipx\pipx\venvs\insanely-fast-whisper\Lib\site-packages\transformers\pipelines\automatic_speech_recognition.py", line 239, in __init__
    self.model.to(device)
  File "C:\Users\XX\AppData\Local\pipx\pipx\venvs\insanely-fast-whisper\Lib\site-packages\transformers\modeling_utils.py", line 2460, in to
    return super().to(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\AppData\Local\pipx\pipx\venvs\insanely-fast-whisper\Lib\site-packages\torch\nn\modules\module.py", line 1160, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\AppData\Local\pipx\pipx\venvs\insanely-fast-whisper\Lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  File "C:\Users\XX\AppData\Local\pipx\pipx\venvs\insanely-fast-whisper\Lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  File "C:\Users\XX\AppData\Local\pipx\pipx\venvs\insanely-fast-whisper\Lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  File "C:\Users\XX\AppData\Local\pipx\pipx\venvs\insanely-fast-whisper\Lib\site-packages\torch\nn\modules\module.py", line 833, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "C:\Users\XX\AppData\Local\pipx\pipx\venvs\insanely-fast-whisper\Lib\site-packages\torch\nn\modules\module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XX\AppData\Local\pipx\pipx\venvs\insanely-fast-whisper\Lib\site-packages\torch\cuda\__init__.py", line 289, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

~ took 12s
❯
```

**Comment by Vaibhavs10** [comment]
Hi @afiaka87, @astrowonk & @oenu This should fixed in the latest patch to insanely-fast-whisper. 
The issue crept up due to an update in optimum: https://github.com/huggingface/optimum/pull/1590
Make sure to get the most recent version of `insanely-fast-whisper`:
1. `pipx uninstall insanely-fast-whisper`
2. `pipx install insanely-fast-whisper==0.0.13 --force`

@oenu - regarding your windows issue do make sure to checkout the second FAQ: https://github.com/Vaibhavs10/insanely-fast-whisper#frequently-asked-questions (you'd need to manually install this into your virtualenv)

**Comment by oenu** [comment]
> @oenu - regarding your windows issue do make sure to checkout the second FAQ: https://github.com/Vaibhavs10/insanely-fast-whisper#frequently-asked-questions (you'd need to manually install this into your virtualenv)

Ah, ty, will check out

Also +1 for the fast fix above!
