### ISSUE TITLE
"No module named wheel" when adding flash-attn on Windows

### ISSUE THREAD

**Issue by jenny923432** [Vaibhavs10/insanely-fast-whisper#226]
Using insanely-fast-whisper 0.0.13, Python 3.11.4, pipx 1.5.0.

```
$ pipx install insanely-fast-whisper --force --pip-args="--ignore-requires-python"
$ pipx runpip insanely-fast-whisper install flash-attn --no-build-isolation


Collecting flash-attn
  Using cached flash_attn-2.5.8.tar.gz (2.5 MB)
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  ├ù Preparing metadata (pyproject.toml) did not run successfully.
  Γöé exit code: 1
  Γò░ΓöÇ> [17 lines of output]
      Traceback (most recent call last):
        File "C:\Users\gal\pipx\shared\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\gal\pipx\shared\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\gal\pipx\shared\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\gal\pipx\venvs\insanely-fast-whisper\Lib\site-packages\setuptools\build_meta.py", line 366, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "C:\Users\gal\pipx\venvs\insanely-fast-whisper\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "C:\Users\gal\pipx\venvs\insanely-fast-whisper\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 17, in <module>
      ModuleNotFoundError: No module named 'wheel'
      [end of output]
```

'wheel' is available normally:

```
$ python -m wheel version
wheel 0.43.0
```

`python -m pipx install wheel` doesn't help. I couldn't find any information about this error here, I'm sure I'm missing something but what could it be?

**Comment by neon-ninja** [comment]
Try `pipx runpip insanely-fast-whisper install wheel`
