### ISSUE TITLE
Initial testing lead to a crash, FYI in case this is of use.

### ISSUE THREAD

**Issue by walt93** [Vaibhavs10/insanely-fast-whisper#52]
```
$ insanely-fast-whisper --file-name 2023-11-15\ 10.45.06.mp4
Traceback (most recent call last):
  File "/home/administrator/PodVision/venv-ai/bin/insanely-fast-whisper", line 8, in <module>
    sys.exit(main())
  File "/home/administrator/PodVision/venv-ai/lib/python3.10/site-packages/insanely_fast_whisper/cli.py", line 86, in main
    pipe = pipeline(
  File "/home/administrator/PodVision/venv-ai/lib/python3.10/site-packages/transformers/pipelines/__init__.py", line 885, in pipeline
    tokenizer = AutoTokenizer.from_pretrained(
  File "/home/administrator/PodVision/venv-ai/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 691, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
  File "/home/administrator/PodVision/venv-ai/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1825, in from_pretrained
    return cls._from_pretrained(
  File "/home/administrator/PodVision/venv-ai/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 1857, in _from_pretrained
    slow_tokenizer = (cls.slow_tokenizer_class)._from_pretrained(
  File "/home/administrator/PodVision/venv-ai/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2044, in _from_pretrained
    raise ValueError(
ValueError: Non-consecutive added token '<|0.02|>' found. Should have index 50365 but has index 50366 in saved vocabulary.

$ python --version
Python 3.10.8

$ nvidia-smi
Wed Nov 15 22:11:42 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.76       Driver Version: 515.76       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA T1000 8GB    Off  | 00000000:03:00.0 Off |                  N/A |
| 32%   45C    P0    N/A /  50W |      0MiB /  8192MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal
```

Tried a couple of different input files, crash occurs in the same location.

**Comment by Vaibhavs10** [comment]
@walt93 you're passing a `mp4` file. `insanely-fast-whisper` repo only supports audio.
