### ISSUE TITLE
issue while installing it on ubantu macihine

### ISSUE THREAD

**Issue by akashAD98** [Vaibhavs10/insanely-fast-whisper#64]
pip install pipx
pipx install insanely-fast-whisper

python 3.10 used for this 
still getting this issue ,how can i solve it??
```
Traceback (most recent call last):
  File "/home/faster_whisper.py", line 1, in <module>
    from faster_whisper import WhisperModel
  File "/home/faster_whisper.py", line 1, in <module>
    from faster_whisper import WhisperModel
ImportError: cannot import name 'WhisperModel' from partially initialized module 'faster_whisper' (most like
```

**Comment by Vaibhavs10** [comment]
This is weird, we don't use `faster-whisper`.
Can you just run `pipx run insanely-fast-whisper --file-name <filename or URL to a audio file>`

**Comment by akashAD98** [comment]
@Vaibhavs10 ill try it .but my man goal is to run it on local system or make python service.i cant use cli for it

**Comment by akashAD98** [comment]
this is error im getting. may i know which python version is working with it? any otjer method to install requirements.txt?
can you add it 
![image](https://github.com/Vaibhavs10/insanely-fast-whisper/assets/62583018/994c2df7-9a10-4b15-9c4b-2b732e142dac)

**Comment by Vaibhavs10** [comment]
Hi @akashAD98 - I don't really know why it isn't running for you, it looks like an Internet connection issue. The install from `insanely-fast-whisper` side works fine.
