### ISSUE TITLE
Error installing insanely-fast-whisper on M1 Mac even after several retries

### ISSUE THREAD

**Issue by RayFernando1337** [Vaibhavs10/insanely-fast-whisper#66]
**Invocation**
`pipx install insanely-fast-whisper`

**Console Output**
Fatal error from pip prevented installation. Full pip output in file:
    /Users/ray/.local/pipx/logs/cmd_2023-11-22_10.36.26_pip_errors.log

pip seemed to fail to build package:

    optimum

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    FileNotFoundError: [Errno 2] No such file or directory: 'optimum/version.py'
    AssertionError: Error: Could not open 'optimum/version.py' due [Errno 2] No such file or directory: 'optimum/version.py'

Error installing insanely-fast-whisper.

**Error Log**
[cmd_2023-11-22_10.36.26_pip_errors.log](https://github.com/Vaibhavs10/insanely-fast-whisper/files/13444165/cmd_2023-11-22_10.36.26_pip_errors.log)
```Downloading optimum-0.1.2-py3-none-any.whl (33 kB)
  Downloading optimum-0.1.1.tar.gz (17 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
  Downloading optimum-0.1.0.tar.gz (16 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'```

PIP STDERR
----------
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out. (read timeout=15)")': /packages/dc/0c/f95215bc5f65e0a5fb97d4febce7c18420002a4c3ea5182294dc576f17fb/accelerate-0.16.0-py3-none-any.whl
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      Traceback (most recent call last):
        File "<string>", line 7, in <module>
      FileNotFoundError: [Errno 2] No such file or directory: 'optimum/version.py'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/Users/ray/.local/pipx/shared/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/ray/.local/pipx/shared/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/ray/.local/pipx/shared/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/gf/74t2xp_90_bgkn8nhp74xkn00000gn/T/pip-build-env-lyfsyn4h/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/gf/74t2xp_90_bgkn8nhp74xkn00000gn/T/pip-build-env-lyfsyn4h/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/gf/74t2xp_90_bgkn8nhp74xkn00000gn/T/pip-build-env-lyfsyn4h/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/private/var/folders/gf/74t2xp_90_bgkn8nhp74xkn00000gn/T/pip-build-env-lyfsyn4h/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 10, in <module>
      AssertionError: Error: Could not open 'optimum/version.py' due [Errno 2] No such file or directory: 'optimum/version.py'
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.```

**Comment by patrick91** [comment]
Can you try on Python 3.11? I think optimum might not work on 3.12 just yet :)

**Comment by sarchak** [comment]
Getting same error even with 3.11.6

**Comment by hanimedialab** [comment]
same error with python 3.11.4

**Comment by haeds** [comment]
I encountered the same issue and managed to resolve it successfully. Here's the step-by-step process I followed:

1. **Create a new Conda environment:**
   ```bash
   conda create --name insanely-fast-whisper python=3.11
   ```
2. **Activate the newly created environment:**
   ```bash
   conda activate insanely-fast-whisper
   ```
3. **Install the 'optimum' package using pip:**
   ```bash
   python -m pip install optimum
   ```
4. **Clone the repository from GitHub:**
   ```bash
   git clone https://github.com/Vaibhavs10/insanely-fast-whisper.git
   ```
5. **Navigate into the cloned repository directory:**
   ```bash
   cd insanely-fast-whisper
   ```
6. **Install the required dependencies:**
   ```bash
   pip install .
   ```

After completing these steps, I was able to run `insanely-fast-whisper` successfully with the following command:

```bash
insanely-fast-whisper --file-name sample.mp3 --device-id mps --batch-size 2
```

I hope this helps others facing the same issue.

**Comment by hanimedialab** [comment]
Thanks, haeds. But I have encountered another error, lol.

raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enable

How can I solve it? :(

**Comment by haeds** [comment]
> Thanks, haeds. But I have encountered another error, lol.
> 
> raise AssertionError("Torch not compiled with CUDA enabled") AssertionError: Torch not compiled with CUDA enable
> 
> How can I solve it? :(

Could you please confirm if you included the --device-id mps parameter in your command line?

**Comment by patrick91** [comment]
if you have the same issue on python3.11 can you post the full logs?

I can reproduce the issue on 3.12, but not on 3.11
