### ISSUE TITLE
speaker diarise: ValueError: attempt to get argmin of an empty sequence

### ISSUE THREAD

**Issue by eschmidbauer** [Vaibhavs10/insanely-fast-whisper#76]
diarise is not working when running cli with
```python cli.py --device-id cuda:0 --batch-size 1 --timestamp word --file-name mono.wav  --hf_token XXXXXXX```

![image](https://github.com/Vaibhavs10/insanely-fast-whisper/assets/7139998/7107ae3c-4ad4-4e6d-b9de-a4a9e41ade8a)

```
🤗 Transcribing... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0:00:20
Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
🤗 Transcribing... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0:00:20
🤗 Segmenting... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0:00:01
Traceback (most recent call last):
  File "/home/user/cli.py", line 282, in <module>
    segmented_transcript = post_process_segments_and_transcripts(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/cli.py", line 128, in post_process_segments_and_transcripts
    upto_idx = np.argmin(np.abs(end_timestamps - end_time))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/insanely-fast-whisper/lib/python3.11/site-packages/numpy/core/fromnumeric.py", line 1325, in argmin
    return _wrapfunc(a, 'argmin', axis=axis, out=out, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/envs/insanely-fast-whisper/lib/python3.11/site-packages/numpy/core/fromnumeric.py", line 59, in _wrapfunc
    return bound(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^
ValueError: attempt to get argmin of an empty sequence
```

**Comment by Vaibhavs10** [comment]
This is a bug in the implementation. I'll push a fix tomorrow 🤗 
Thanks for reporting this!

**Comment by rbracco** [comment]
A quick hacky fix in case someone needs it between now and when it's PR'd is to change part of CLI.py from

```
def post_process_segments_and_transcripts(new_segments, transcript, group_by_speaker):
    end_timestamps = np.array([chunk["timestamp"][-1] for chunk in transcript])
    segmented_preds = []
```

```
def post_process_segments_and_transcripts(new_segments, transcript, group_by_speaker):
    end_timestamps = np.array([chunk["timestamp"][-1] for chunk in transcript])
    if end_timestamps[-1] is None:
        end_timestamps[-1] = new_segments[-1]["segment"]["end"]
    segmented_preds = []
```

Be aware that this may result in the final segment of the transcription being imprecise, as I didnt really dig for the root of the problem, but it will fix the bug and every other segment (every one but the last one) will remain correct and unaltered.

**Comment by SivaKanishka** [comment]
Seems like the error still persists. I installed the package using pipx. @Vaibhavs10 do you suggest to install this from source?

**Comment by Vaibhavs10** [comment]
Wow! thanks @rbracco - this should work for now!

@SivaKanishka - Till the time we make a new release I think you're better off making these changes yourself and installing from source.

Sorry a bit short on time today/ tomorrow.

**Comment by SivaKanishka** [comment]
> Wow! thanks @rbracco - this should work for now!
> 
> @SivaKanishka - Till the time we make a new release I think you're better off making these changes yourself and installing from source.
> 
> Sorry a bit short on time today/ tomorrow.

Thanks @Vaibhavs10. Will make changes on my end

**Comment by bluusun** [comment]
Same error for the pip -U install:

🤗 Segmenting... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0:00:49
Traceback (most recent call last):
  File "/usr/local/bin/insanely-fast-whisper", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/insanely_fast_whisper/cli.py", line 280, in main
    segmented_transcript = post_process_segments_and_transcripts(
  File "/usr/local/lib/python3.10/site-packages/insanely_fast_whisper/cli.py", line 127, in post_process_segments_and_transcripts
    upto_idx = np.argmin(np.abs(end_timestamps - end_time))
  File "<__array_function__ internals>", line 180, in argmin
  File "/usr/local/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 1312, in argmin
    return _wrapfunc(a, 'argmin', axis=axis, out=out, **kwds)
  File "/usr/local/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
ValueError: attempt to get argmin of an empty sequence
root@C.7739141:~$

**Comment by Vaibhavs10** [comment]
This should be fixed with the latest release of `insanely-fast-whisper`. Feel free to upgrade it! 🤗

**Comment by bluusun** [comment]
No changes :(

Name: insanely-fast-whisper
Version: 0.0.12
Summary: An insanely fast whisper CLI
Home-page: 
Author: 
License: MIT
Location: /usr/local/lib/python3.10/site-packages
Requires: accelerate, optimum, pyannote-audio, rich, setuptools, transformers
Required-by: 

🤗 Segmenting... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0:00:59
Traceback (most recent call last):
  File "/usr/local/bin/insanely-fast-whisper", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/insanely_fast_whisper/cli.py", line 132, in main
    speakers_transcript = diarize(args, outputs)
  File "/usr/local/lib/python3.10/site-packages/insanely_fast_whisper/utils/diarization_pipeline.py", line 29, in diarize
    return post_process_segments_and_transcripts(
  File "/usr/local/lib/python3.10/site-packages/insanely_fast_whisper/utils/diarize.py", line 124, in post_process_segments_and_transcripts
    upto_idx = np.argmin(np.abs(end_timestamps - end_time))
  File "<__array_function__ internals>", line 180, in argmin
  File "/usr/local/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 1312, in argmin
    return _wrapfunc(a, 'argmin', axis=axis, out=out, **kwds)
  File "/usr/local/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
ValueError: attempt to get argmin of an empty sequence

It does run longer before encountering an error now (about 59 seconds for me).

**Comment by bluusun** [comment]
Ran the same file directly through pyannote-audio and got results just fine...

**Comment by bluusun** [comment]
FWIW decided to do my own scripts and run pyannote separately. Combining the two outputs wasn't easy I admit. Maybe it should not be part of ifw?
