### ISSUE TITLE
Diarization step crashing if Whisper failed to predict end_timestamp

### ISSUE THREAD

**Issue by Sehyo** [Vaibhavs10/insanely-fast-whisper#91]
Whisper did not predict an ending timestamp, this consequently makes the diarization step fail.
```
🤗 Transcribing... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0:00:15Whisper did not predict an ending timestamp, which can happen if audio is cut off in the middle of a word. Also make sure WhisperTimeStampLogitsProcessor was used during generation.
🤗 Transcribing... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0:00:15
🤗 Segmenting... ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0:00:12
Traceback (most recent call last):
  File "/home/tiefighter/.local/bin/insanely-fast-whisper", line 8, in <module>
    sys.exit(main())
  File "/home/tiefighter/.local/lib/python3.10/site-packages/insanely_fast_whisper/cli.py", line 280, in main
    segmented_transcript = post_process_segments_and_transcripts(
  File "/home/tiefighter/.local/lib/python3.10/site-packages/insanely_fast_whisper/cli.py", line 127, in post_process_segments_and_transcripts
    upto_idx = np.argmin(np.abs(end_timestamps - end_time))
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
```

**Comment by Vaibhavs10** [comment]
Hey @Sehyo - Thanks for reporting this, this is a known issue. I will hack together a more durable fix to this over the weekend.
In the meantime there is a proposed solution here: https://github.com/Vaibhavs10/insanely-fast-whisper/issues/76#issuecomment-1832854702

If it's alright then let's use that issue to track the status of this.

(I'll close this issue in the favour of https://github.com/Vaibhavs10/insanely-fast-whisper/issues/76)
